CREATE TABLE podcasts (
	id INT PRIMARY KEY AUTO_INCREMENT,
    archivo VARCHAR(15) NOT NULL,
    obs VARCHAR(120)
);

CREATE TABLE sources (
	id INT PRIMARY KEY AUTO_INCREMENT,
    url VARCHAR(120)
);

